### ISSUE TITLE
Counselor Queries

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-graphql-api#13]
Add the resolvers necessary to deliver Counselors data from MongoDB.

* [x] Make sure __counselors__ collection exists in database
* [x] Modify Schema
* [x] Stub Resolvers
* [x] Query - `totalCounselors`
* [x] Query - `allCounselors`
* [x] Query - `Counselor`
* [x] Query - add type argument to `totalCounselors` and `allCounselors`
* [x] Integration Tests
* [x] Unit Tests
* [x] Scema Documentation

```graphql
enum Rank {
    SCOUT
    WARRIOR
    CHIEF
}

type Photo {
    full: String
    thumb: String
}

type Counselor {
    id: ID!
    name: String!
    photo: Photo
    bio: String
    rank: Rank
    twitterHandle: String
    githubHandle: String
}

type Query {
    totalCounselors(rank: Rank): Int!
    allCounselors(rank: Rank): [Counselor!]!
    Counselor(id: ID!): Counselor
}
```

**Comment by eveporcello** [comment]
Updating the schema to reflect agreed upon 2018 best practices when it comes to schemas and cultural sensitivity:

```
enum Rank {
    ALPHA
    BETA
    RELEASE_CANDIDATE
}

type Photo {
    full: String
    thumb: String
}

type Counselor {
    id: ID!
    name: String!
    photo: Photo
    bio: String
    rank: Rank
    twitterHandle: String
    githubHandle: String
}

type Query {
    totalCounselors(rank: Rank): Int!
    allCounselors(rank: Rank): [Counselor!]!
    findCounselorById(id: ID!): Counselor
}
```
