### ISSUE TITLE
Environment Var Solution Buggy

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-graphql-api#44]
The environemnt

1. Test query `githubAuthUrl` locally using `dev:start`
2. Sometimes it says Github is not configured
3. For some reason it works if there is a console log, it doesn't if not

Make sure the webpack build works too, and that it is not getting in the way.

**Comment by eveporcello** [comment]
Hard coded `SECRET` and `MONGODB_URI` for now
