### ISSUE TITLE
Identify Solution for Image Hosting

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-graphql-api#9]
Find a host and add all of the necessary static images to that host

* [x] Find a Place to host static images
* [x] Host Images
    * [x] Counselor photos
    * [x] Cabin photos
    * [ ] Activity photos

related #8 
related #7

**Comment by MoonTahoe** [comment]
Can you setup the Cloudinary space and add a couple of pictures to it and place links to those photos here.

**Comment by eveporcello** [comment]
https://res.cloudinary.com/hmaz4q3oh/image/upload/v1539911574/counselors/kyle-shevlin.jpg
https://res.cloudinary.com/hmaz4q3oh/image/upload/v1539911475/counselors/andrew-del-prete.jpg
https://res.cloudinary.com/hmaz4q3oh/image/upload/v1539911574/counselors/kent-c-dodds.jpg

**Comment by MoonTahoe** [comment]
Great. That's a long string, damn. The next step is to get ALL, EVERY, all of the images that we need hosted on this thing so we can add the appropriate urls to the database.

**Comment by eveporcello** [comment]
Closing this as it's solved for counselors & cabins. Just need to populate activities which is handled by #8
